In [12]:
# %load imports
import numpy as np
import scipy as sp
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib as mpl
%matplotlib inline
import seaborn as sns
sns.set()

In [13]:
df1 = pd.DataFrame(
[
    ['red', 5, 10],
    ['blue', 8, 16],
    ['green', 14, 32],
], columns="color v1 v2".split()
)

In [14]:
df2 = pd.DataFrame(
[
    ['purple', 11, 6],
    ['orange', 85, 32],
    ['black', 44, 20],
], columns="color v1 v3".split()
)

In [15]:
df3 = pd.DataFrame(
[
    ['red', 19, 10],
    ['blue', 8, 16],
    ['pink', 14, 32],
], columns="color v1 v2".split()
)

In [16]:
df1

   color  v1  v2
0    red   5  10
1   blue   8  16
2  green  14  32

In [17]:
df2

    color  v1  v3
0  purple  11   6
1  orange  85  32
2   black  44  20

In [18]:
df1 + df2

        color  v1  v2  v3
0   redpurple  16 NaN NaN
1  blueorange  93 NaN NaN
2  greenblack  58 NaN NaN

In [19]:
pd.merge(df1, df2, how="outer")

    color  v1    v2    v3
0     red   5  10.0   NaN
1    blue   8  16.0   NaN
2   green  14  32.0   NaN
3  purple  11   NaN   6.0
4  orange  85   NaN  32.0
5   black  44   NaN  20.0

In [20]:
pd.merge(df1, df2, how="inner")

Empty DataFrame
Columns: [color, v1, v2, v3]
Index: []

In [21]:
pd.merge(df1, df2, how='cross')

  color_x  v1_x  v2 color_y  v1_y  v3
0     red     5  10  purple    11   6
1     red     5  10  orange    85  32
2     red     5  10   black    44  20
3    blue     8  16  purple    11   6
4    blue     8  16  orange    85  32
5    blue     8  16   black    44  20
6   green    14  32  purple    11   6
7   green    14  32  orange    85  32
8   green    14  32   black    44  20

In [22]:
pd.merge(df1, df3)

  color  v1  v2
0  blue   8  16

In [23]:
pd.merge(df1, df3, how="inner")

  color  v1  v2
0  blue   8  16

In [24]:
pd.merge(df1, df3, how="outer")

   color  v1  v2
0    red   5  10
1   blue   8  16
2  green  14  32
3    red  19  10
4   pink  14  32

In [25]:
pd.merge(df1, df3, how="cross")

  color_x  v1_x  v2_x color_y  v1_y  v2_y
0     red     5    10     red    19    10
1     red     5    10    blue     8    16
2     red     5    10    pink    14    32
3    blue     8    16     red    19    10
4    blue     8    16    blue     8    16
5    blue     8    16    pink    14    32
6   green    14    32     red    19    10
7   green    14    32    blue     8    16
8   green    14    32    pink    14    32